[LegalNotice]
Accepted=true

[Preferences]
Advanced\RecheckOnCompletion=false
Bittorrent\DHT=false
Bittorrent\PeX=false
Bittorrent\LSD=false
Connection\ProxyType=2
Connection\Proxy\ProxyAddress=10.10.10.1
Connection\Proxy\ProxyPort=4447
Connection\Proxy\ProxyPeerConnections=true
Connection\Proxy\ForceProxy=true
Downloads\PreAllocation=false
Downloads\SavePath=/root/torrents
Downloads\TempPath=/root/torrents/tmp
Downloads\ScanDirsV2=@Variant(\0\0\0\x1c\0\0\0\0)
WebUI\Enabled=false
