port = 25432
ipv4 = true
ipv6 = false
bandwidth = 512
share = 10
loglevel = info
notransit = false

[httpproxy]
enabled = true
address = 0.0.0.0
port = 4444
inbound.length = 1
outbound.length = 1
inbound.quantity = 3
outbound.quantity = 3

[socksproxy]
enabled = true
address = 0.0.0.0
port = 4447
inbound.length = 1
outbound.length = 1
inbound.quantity = 3
outbound.quantity = 3

[limits]
transittunnels = 10
openfiles = 0
coresize = 0

[exploratory]
inbound.length = 1
inbound.quantity = 3
outbound.length = 1
outbound.quantity = 3

[ntcp2]
enabled = true
published = false

[ssu2]
enabled = true
published = false

[http]
enabled = true
address = 0.0.0.0
port = 7070

[reseed]
verify = false
urls = https://reseed.stormycloud.org/i2pseeds.su3,https://reseed.i2p-projekt.de/,https://i2p.mooo.com/netDb/

[upnp]
enabled = false
